# Generated by Django 5.2.6 on 2025-09-23 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="account_type",
            field=models.CharField(
                choices=[("job_seeker", "Job Seeker"), ("recruiter", "Recruiter")],
                default="job_seeker",
                max_length=20,
            ),
        ),
    ]
