# Generated by Django 5.0 on 2025-09-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_jobseekerprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobseekerprofile',
            name='commute_radius',
            field=models.PositiveIntegerField(blank=True, help_text='Preferred commute radius in miles', null=True),
        ),
    ]
