# Generated by Django 5.2.6 on 2025-10-25 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_savedsearch_searchnotification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="savedsearch",
            name="email_notifications",
        ),
        migrations.RemoveField(
            model_name="savedsearch",
            name="last_notification_sent",
        ),
        migrations.AddField(
            model_name="savedsearch",
            name="last_check",
            field=models.DateTimeField(
                blank=True, help_text="Last time matches were checked", null=True
            ),
        ),
        migrations.CreateModel(
            name="TalentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("new_match", "New Match"),
                            ("profile_update", "Profile Update"),
                        ],
                        default="new_match",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.jobseekerprofile",
                    ),
                ),
                (
                    "recruiter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="talent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "saved_search",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="accounts.savedsearch",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("saved_search", "profile", "message_type")},
            },
        ),
        migrations.DeleteModel(
            name="SearchNotification",
        ),
    ]
