# Generated by Django 5.2.8 on 2025-11-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_conversation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='other_skills',
            field=models.TextField(blank=True, help_text='Comma-separated other skills entered by recruiter'),
        ),
    ]
