# Generated by Django 5.2.6 on 2025-11-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_savedsearch_other_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_bio",
            field=models.BooleanField(default=True, help_text="Show bio to recruiters"),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_education",
            field=models.BooleanField(
                default=True, help_text="Show education to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_experience",
            field=models.BooleanField(
                default=True, help_text="Show experience to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_github",
            field=models.BooleanField(
                default=True, help_text="Show GitHub URL to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_headline",
            field=models.BooleanField(
                default=True, help_text="Show headline to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_linkedin",
            field=models.BooleanField(
                default=True, help_text="Show LinkedIn URL to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_location",
            field=models.BooleanField(
                default=True, help_text="Show location to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_portfolio",
            field=models.BooleanField(
                default=True, help_text="Show portfolio URL to recruiters"
            ),
        ),
        migrations.AddField(
            model_name="jobseekerprofile",
            name="show_skills",
            field=models.BooleanField(
                default=True, help_text="Show skills to recruiters"
            ),
        ),
    ]
