# Generated by Django 5.2.6 on 2025-10-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"ordering": ["position_in_stage", "-updated_at"]},
        ),
        migrations.AddField(
            model_name="application",
            name="flagged",
            field=models.BooleanField(
                default=False, help_text="Flag important candidates"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="position_in_stage",
            field=models.PositiveIntegerField(
                default=0, help_text="Order within status column"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="recruiter_notes",
            field=models.TextField(
                blank=True, help_text="Internal notes for recruiter use only"
            ),
        ),
        migrations.AddField(
            model_name="application",
            name="stage_changed_at",
            field=models.DateTimeField(
                blank=True, help_text="When status last changed", null=True
            ),
        ),
    ]
