# Generated by Django 5.0 on 2025-11-21 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_application_options_application_flagged_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='moderated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_reason',
            field=models.TextField(blank=True, help_text='Optional reason explaining why moderation status was changed'),
        ),
        migrations.AddField(
            model_name='job',
            name='moderation_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending Review'), ('flagged', 'Flagged'), ('removed', 'Removed')], default='active', help_text='Moderation status to control visibility', max_length=20),
        ),
    ]
